version: '3.8'

services:
  accounts:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///./accounts.db
      - SECRET_KEY=your-secret-key-for-development
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
