apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-service
  namespace: iodv3-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-service
  template:
    metadata:
      labels:
        app: blog-service
    spec:
      containers:
      - name: blog-service
        image: iodv3/blog-service:dev
        ports:
        - containerPort: 8002
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:password@postgres-service:5432/iodv3_blog"
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: ACCOUNTS_SERVICE_URL
          value: "http://accounts-service:8001"
        envFrom:
        - configMapRef:
            name: app-config
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: blog-service
  namespace: iodv3-dev
spec:
  selector:
    app: blog-service
  ports:
  - port: 8002
    targetPort: 8002
    nodePort: 30002
  type: NodePort
